Migrate continuous integration to GitHub actions (fixes #652)
mozilla/protocol pull request #690
Opened 2021-05-18 18:58 UTC by wlach

This is more urgent now that [travis ci is shutting down for real](https://blog.travis-ci.com/2021-05-07-orgshutdown)

## Description

Describe what this change does.

- [x] (N/A) I have documented this change in the design system.
- [x] I have recorded this change in `CHANGELOG.md`.

### Issue

This fixes #652 

### Testing

N/A, check ci status

2021-05-18 19:20 UTC, wlach commented
Seems to work on my fork: https://github.com/wlach/protocol/actions/runs/854424933

2021-05-20 23:23 UTC, craigcook commented
This looks good to me and works in my testing, but I'm outside my wheelhouse.
@pmac Could you give this a look when you've got a minute, make sure we're not missing something?

2021-05-21 16:10 UTC, craigcook requested changes

2021-05-21 16:10 UTC, craigcook commented on .github/workflows/node.js.yml
> +        node-version: [10.x, 12.x, 14.x, 15.x]
Our minimum Node version will bump up to 12.x in https://github.com/mozilla/protocol/pull/691, so we can drop 10.x from this list.

2021-05-21 17:45 UTC, wlach commented on .github/workflows/node.js.yml
> +        node-version: [10.x, 12.x, 14.x, 15.x]
```suggestion
        node-version: [12.x, 14.x, 15.x]
```

2021-06-04 22:12 UTC, craigcook approved these changes

2021-06-04 22:13 UTC, merged