had rules to card with mzp-t-dark class
mozilla/protocol pull request #715
Opened 2021-09-03 21:37 UTC by nathan-barrett

## Description
Added some rules when adding the `.mzp-t-dark` class to enable dark mode styled cards. I used the same themes as in other areas of protocol, but let me know if anything should change. 

Added some rules to override the links and `p` tags in the card component so the color would be visible for dark mode.

- [ ] I have documented this change in the design system.
- [ x] I have recorded this change in `CHANGELOG.md`.

### Issue
#714
Add a link to a related GitHub issue if applicable.

### Testing
Wasn't sure how we would want to add this card _variant_ to the documentation since dark mode is only referenced in the themes section of the docs. If you build this locally, you can just add the `.mzp-t-dark` class to any card in the docs.

2021-09-03 21:40 UTC, nathan-barrett commented on CHANGELOG.md
> +* **css:** Added overidding rules to the card component to enable dark mode with `.mzp-t-dark` class.
Can change this to `Add` before merge

2021-09-07 22:49 UTC, nathan-barrett commented
@alexgibson let me know what you think - the color followed the `color-inverse` theme already in place in protocol, but I wasn't sure if that's the one we wanted.

2021-09-08 01:03 UTC, craigcook requested changes
We should mention the dark theme in the docs on the component page, and maybe include an example on one of the demo pages.

2021-09-08 01:03 UTC, craigcook commented on src/assets/sass/protocol/components/_card.scss
> +.mzp-c-card.mzp-t-dark {
We should also add a selector that lets cards in a dark container take on the theme:
```suggestion
.mzp-c-card.mzp-t-dark,
.mzp-t-dark .mzp-c-card {
```

2021-09-08 01:03 UTC, craigcook commented on CHANGELOG.md
> +* **css:** Add overidding rules to the card component to enable dark mode with `.mzp-t-dark` class.
Typo: overriding

2021-09-13 18:14 UTC, craigcook requested changes

2021-09-13 18:14 UTC, craigcook commented on src/pages/demos/card-layout.hbs
> +<div class="mzp-l-content">
I think the demo will be more effective if we make the container dark:
```suggestion
<div class="mzp-l-content mzp-t-dark">
```

2021-09-13 18:14 UTC, craigcook commented on src/pages/demos/card-layout.hbs
> +    {{#embed "patterns.molecules.card.small-card" class="mzp-t-dark"}}{{/embed}}
Actually, I just noticed the medium card include also adds a tag with an icon, but we don't have any light icons in Protocol (we need to update all the icons anyway, but that's a whole other thing) so it doesn't look great as a demo. 

![image](https://user-images.githubusercontent.com/205591/133134857-122dda9e-c368-47bf-9044-699e6e95c04e.png)

So maybe we stick with the small molecule but pass it the medium class explicitly (which is all the medium card include does anyway):

```suggestion
    {{#embed "patterns.molecules.card.small-card" class="mzp-c-card-medium mzp-has-aspect-3-2"}}{{/embed}}
```

2021-09-13 23:17 UTC, craigcook approved these changes

2021-09-13 23:18 UTC, merged