Update dependencies
mozilla/protocol pull request #726
Opened 2021-09-20 21:46 UTC by craigcook

## Description
Updates various dependencies, should address some security alerts (at least until we can migrate off Drizzle).

This also fixes #722 by adding dart-sass and replacing all our `/` division operators (which was fewer than I thought).

2021-09-21 13:40 UTC, maureenlholland requested changes
Looks good! Needs a changelog note, then r+

2021-09-21 15:36 UTC, maureenlholland commented
oh hang on, poor review on my part, there might be a few more `/` operators lurking
<img width="446" alt="Screen Shot 2021-09-21 at 4 29 33 PM" src="https://user-images.githubusercontent.com/19650432/134201228-f4da1c49-55b9-4b9b-b777-98763bedd8c0.png">

2021-09-21 15:52 UTC, craigcook commented
Huh. The migration tool didn't find those and they don't raise deprecation warnings, so evidently Sass doesn't recognize when we do math with tokens. I'll fix them and see if I can find any more.

2021-09-22 11:21 UTC, maureenlholland approved these changes
r++ 💠

2021-09-22 11:21 UTC, maureenlholland commented on src/assets/sass/protocol/components/_footer.scss
> +            width: calc($width - ($layout-md - $gutter));
Lovely upgrade for sass and readability!

2021-09-22 14:38 UTC, merged